version: "3.7"
services:
  # image project
  app_api:
    container_name: app_api_app_laravel
    build:
      args:
        user: api_app
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ././api/:/var/www
    depends_on:
      - redis
      - queue
    networks:
      - appnetwork

  # nginx
  nginx:
    container_name: app_nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ././api/:/var/www
      - ././api/docker/nginx/:/etc/nginx/conf.d/
    networks:
      - appnetwork

  # db mysql
  mysql:
    container_name: app_mysql
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dhxy8hkIDP&Y
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - appnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - appnetwork

  # queue
  queue:
    build:
      args:
        user: api_app
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: app_queue
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ././api/:/var/www
    depends_on:
      - redis
    networks:
      - appnetwork

  # redis
  redis:
    container_name: app_redis
    image: redis:latest
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
