version: "3.7"
services:
  # image project
  teste_dev_app:
    container_name: teste_dev_app_laravel
    build:
      args:
        user: gabriel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: teste-dev-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - queue
    networks:
      - teste_dev_network

  # nginx
  nginx:
    container_name: teste_dev_nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - teste_dev_network

  # db mysql
  mysql:
    container_name: teste_dev_mysql
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dhxy8hkIDP&Y
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - teste_dev_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8002:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - teste_dev_network

  # queue
  queue:
    build:
      args:
        user: gabriel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: teste_dev_queue
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - teste_dev_network

  # redis
  redis:
    container_name: teste_dev_redis
    image: redis:latest
    networks:
      - teste_dev_network

networks:
  teste_dev_network:
    driver: bridge
